"""Fix relationships in Player and PlayerEvent

Revision ID: c6d5a3fa936e
Revises: c1827997c8d1
Create Date: 2024-12-20 02:30:47.965170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6d5a3fa936e'
down_revision: Union[str, None] = 'c1827997c8d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
