"""Fix relationships in Player and PlayerEvent

Revision ID: e795ba3b7cde
Revises: dbe641b0840f
Create Date: 2024-12-19 02:57:09.847718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e795ba3b7cde'
down_revision: Union[str, None] = 'dbe641b0840f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
