"""Fix relationships in Player and PlayerEvent

Revision ID: f3a15cdcccd3
Revises: e795ba3b7cde
Create Date: 2024-12-19 03:02:29.429976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3a15cdcccd3'
down_revision: Union[str, None] = 'e795ba3b7cde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
